### ISSUE TITLE
rupdate errors

### ISSUE THREAD

**Issue by pat-s** [rdatsci/rtcl#66]
Arch, r v3.6.1

```sh
rupdate                                                                 

Checking for outdated packages ...
Error: $ operator is invalid for atomic vectors
Warning messages:
1: In utils::packageDescription(name) :
  DESCRIPTION file of package 'mgcv' is missing or broken
```

`~/.config/rt.packages`:

```
rdatsci/rt
```

**Comment by jakob-r** [comment]
Can you check from within R running `rupdate()` and `traceback()`?

**Comment by pat-s** [comment]
```
traceback()
4: FUN(X[[i]], ...)
3: vapply(pkgs_installed$meta, getMetaType, character(1L))
2: rupdate2(x)
1: rt::rupdate()

```

**Comment by jakob-r** [comment]
ok. I might have to write a try then? Is `mgcv` installed in a weird way? Did something bad happen during the installation of `mgcv`?  Reinstalling mgcv will likely resolve this issue but is obiously not the final solution if such a problem occurs more often.

**Comment by pat-s** [comment]
Didn't do anything to `mgcv`. Can be loaded without problems.
Reinstalling did not help.

Let's debug local?
