### ISSUE TITLE
Name clash with package "rt" on CRAN

### ISSUE THREAD

**Issue by jemus42** [rdatsci/rtcl#67]
I was wondering why `rt` was not available in my `$PATH` seemingly at random, even though I could see there was a package named `rt` in my library, but without a `bin` directory.  

Long story short:
My regular updater script called `update.packages()` which saw the package named `rt` and installed the "newer" version from CRAN: https://cran.r-project.org/web/packages/rt/index.html 

This overwrote *this* `rt`, and I had to reinstall it from GitHub.  

I'm not sure what to do about this, but I think there should at least be a note ("caveats"?) in the README about this possible clash and to advise against using `update.packages()` in this case – and of course, users of the CRAN/rt package would find themselves in a particularly annoying spot, I presume.

**Comment by surmann** [comment]
Obviously, we have to rename `rt`. Any suggestions? What about `rtcl`?

**Comment by jakob-r** [comment]
Please Vote using reactions:

* `rtcl` - R Tools for the Command Line :+1:
* `rtls` - R TooLS :smile: 
* `rcl` - R Tools for the Command Line :confused: 
* `rtocool` - R TOols for the CO(O)mmand Line :heart: 
* `clitr` - Command LIne Tools for R :eyes: :

**Comment by surmann** [comment]
A clear vote for `rtcl`? What do you think, @jakob-r ?

If it is ok, I could make a PR to rename the package.

**Comment by surmann** [comment]
A clear vote for `rtcl`? What do you think, @jakob-r ?

If it is ok, I could make a PR to rename the package.

**Comment by surmann** [comment]
See #69.

**Comment by surmann** [comment]
Done

**Comment by surmann** [comment]
I currently rename all bin files.

**Comment by surmann** [comment]
Finished.
